id_to_ftx={
    #crypto
    "ftx-token":       "FTT/USD",
    "solana":          "SOL/USD",
    "bitcoin":         "BTC/USD",
    "ethereum":        "ETH/USD",
    "enjincoin":       "ENJ/USD",
    "fantom":          "FTM/USD",
    "raydium":         "RAY/USD",
    "serum":           "SRM/USD",
    "axie-infinity":   "AXS/USD",

    #stocks

    "AAPL":    "AAPL/USD",
    "ABNB":    "ABNB/USD",
    "ACB":     "ACB/USD",
    "AMC":     "AMC/USD",
    "AMZN":    "AMZN/USD",
    "BABA":    "BABA/USD",
    "BILI":    "BILI/USD",
    "BNTX":    "BNTX/USD",
    "CGC":     "CGC/USD",
    "COIN":    "COIN/USD",
    "CRON":    "CRON/USD",
    "FB":      "FB/USD",
    "GBTC":    "GBTC/USD",
    "GDX":     "GDX/USD",
    "GDXJ":    "GDXJ/USD",
    "GOOGL":   "GOOGL/USD",
    "HOOD":    "HOOD/USD",
    "MRNA":    "MRNA/USD",
    "MSTR":    "MSTR/USD",
    "NFLX":    "NFLX/USD",
    "NIO":     "NIO/USD",
    "PAXG":    "PAXG/USD",
    "PYPL":    "PYPL/USD",
    "SLV":     "SLV/USD",    
    "SQ":      "SQ/USD",
    "TLRY":    "TLRY/USD",
    "TSLA":    "TSLA/USD",
    "TSM":     "TSM/USD",
    "TWTR":    "TWTR/USD",
    "USO":     "USO/USD",
    "ZM":      "ZM/USD",
}
