id_to_poloniex={
    "bitcoin":          "USDT_BTC",
    "dogecoin":         "USDT_DOGE",
    "ethereum":         "USDT_ETH",
    "matic-network":    "USDT_MATIC",
    "ripple":           "USDT_XRP",
    "cardano":          "USDT_ADA",
    "gitcoin":          "USDT_GTC",
    "shiba-inu":        "USDT_SHIB",
    "curve-dao-token":  "USDT_CRV",
    "aave":             "USDT_AAVE",
    "0x":               "USDT_ZRX",
    "havven":           "USDT_SNX",
    "ethereum-classic": "USDT_ETC",
    "polkadot":         "USDT_DOT",
    "basic-attention-token": "USDT_BAT",
}
