---

#
# note:
# to temporarily override settings put them in dca_settings_override.yml
#

# list of known coin ids. By default all coins from this list get accumulated
# when using --add with no additional parameters
coin_ids:
  - bitcoin
  - dogecoin
  - ethereum
  - matic-network
  - cardano
  - ripple
  - solana
  - gitcoin
  - symbol
  - shiba-inu
  - hoge-finance
  - curve-dao-token
  - aave
  - 0x
  - havven
  - ethereum-classic
  - ftx-token
  - decentraland
  - pancakeswap-token

# list of coins NOT to be accumulated when using --add with no additional parameters
auto_accumulate_black_list:
  - cardano
  - matic-network
  - symbol
  - hoge-finance
  - shiba-inu

# map coin id to exchange
coin_exchg:
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  gitcoin:            binance
  shiba-inu:          poloniex
  solana:             ftx
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  ftx-token:          ftx
  decentraland:       binance
  pancakeswap-token:  binance

# base quota, before any reduction
quota_usd: 100

# multiplier applied to base quota
quota_multiplier:
  gitcoin:          1

# accumulate(): max number of order retries, per coin
accumulate_retries: 1
