---

# map asset to exchange
asset_exchg:
  #crypto
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  shiba-inu:          poloniex
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  polkadot:           poloniex
  basic-attention-token: poloniex
  amp-token:          poloniex
  solana:             ftx
  ftx-token:          ftx
  enjincoin:          ftx
  fantom:             ftx
  raydium:            ftx
  serum:              ftx
  axie-infinity:      ftx
  decentraland:       okex
  tezos:              okex
  hedera-hashgraph:   okex
  avalanche-2:        okex
  algorand:           okex
  arweave:            mexc
  cosmos:             mexc
  gitcoin:            mexc
  harmony:            mexc
  #stocks:
  "#AAPL":            ftx  # Apple Inc.
  "#ABNB":            ftx  # Airbnb
  "#ACB":             ftx  # Aurora Cannabis Inc
  "#AMZN":            ftx  # Amazon.com Inc.
  "#BABA":            ftx  # Alibaba Group Hldg (ADR) [China]
  "#BILI":            ftx  # Bilibili Inc. [China] [game publisher]
  "#BNTX":            ftx  # BioNTech
  "#CGC":             ftx  # Canopy Growth Corp
  "#COIN":            ftx  # Coinbase Global Inc.
  "#CRON":            ftx  # Chronos Group Inc
  "#FB":              ftx  # Facebook Inc.
  "#GDX":             ftx  # VanEck Vectors Gold Miners Etf
  "#GDXJ":            ftx  # VanEck Vectors Junior Gold Miners Etf
  "#GOOGL":           ftx  # Alphabet Inc.
  "#HOOD":            ftx  # Robinhood
  "#MRNA":            ftx  # Moderna
  "#MSTR":            ftx  # MicroStrategy Inc.
  "#NFLX":            ftx  # Netflix
  "#NIO":             ftx  # NIO Inc. [China] [electrocars]
  "#PYPL":            ftx  # PayPal Holdings
  "#SQ":              ftx  # Square Inc. [digital payments]
  "#TLRY":            ftx  # Tilray
  "#TSLA":            ftx  # Tesla Inc.
  "#TSM":             ftx  # Taiwan Semiconductor Mfg
  "#TWTR":            ftx  # Twitter Inc.
  "#USO":             ftx  # United States Oil Fund
  "#ZM":              ftx  # Zoom
  #metals:
  "@gold":            ftx
  "@silver":          ftx

# list of assets to be accumulated when using --add with no additional parameters
auto_accumulate_list:
  - 0x
  - aave
  - arweave
  - avalanche-2
  - basic-attention-token
  - cosmos
  - curve-dao-token
  - decentraland
  - enjincoin
  - ethereum-classic
  - fantom
  - ftx-token
  - gitcoin
  - harmony
  - havven
  - hedera-hashgraph
  - polkadot
  - ripple
  - solana
  - tezos
  - raydium
  - serum
  - algorand
  - axie-infinity
  - amp-token
  - matic-network
  - "#BABA"
  - "#BILI"
  - "#COIN"
  - "#NIO"
  - "#TSLA"
  - "#TWTR"
  - "#SQ"
  - "@gold"
  - "@silver"



# default quota for --add per asset if --qty is not specified
quota_usd: 50

# for auto-accumulate: quotas of individual assets will be lowered
# to ensure that sum of their usd value is not exceeding this parameter
total_quota_usd: 500

# applied unconditinally to quota_usd. The final factor is a product of all active factors.
quota_fixed_factor:
  bitcoin:            1.
  ethereum:           1.
  "#AAPL":            0.2
  "#AMZN":            0.2
  "#BABA":            0.2
  "#BILI":            0.2
  "#COIN":            0.2
  "#FB":              0.2
  "#GBTC":            0.2
  "#GOOGL":           0.2
  "#MSTR":            0.2
  "#NIO":             0.2
  "#PYPL":            0.2
  "#TSLA":            0.2
  "#TWTR":            0.2
  "#SQ":              0.2
  "@gold":            1.
  "@silver":          1.

# moving average period to calculate average price to compare current price to
quota_factor_average_days: 200

# quota factor is upper limited to quota_factor_max
quota_factor_max: 2

# is True, asset from auto_accumulate_list is only processed if market is open at the moment
check_market_open: False

# if True, asset from auto_accumulate_list is only processed if close
# is above SMA(close,`avg_days`) by no more than `threshold` %.
check_overprice: False
check_overprice_avg_days: 50
check_overprice_threshold: 1.0

# if True, asset from auto_accumulate_list is only processed if downward movement is detected
check_retracement: True

# list of assets that are not filtered under any condition
no_filter_list:
  - na

# list of asset categories that are not filtered under any condition
no_filter_categories:
  - na
