---

# map asset to exchange
asset_exchg:
  #crypto
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  shiba-inu:          poloniex
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  polkadot:           poloniex
  basic-attention-token: poloniex
  solana:             ftx
  ftx-token:          ftx
  enjincoin:          ftx
  fantom:             ftx
  raydium:            ftx
  serum:              ftx
  decentraland:       okex
  tezos:              okex
  hedera-hashgraph:   okex
  avalanche-2:        okex
  arweave:            mexc
  cosmos:             mexc
  gitcoin:            mexc
  harmony:            mexc
  #stocks:
  "#AAPL":            ftx  # Apple Inc.
  "#AMZN":            ftx  # Amazon.com Inc.
  "#BABA":            ftx  # Alibaba Group Hldg (ADR) [China]
  "#BILI":            ftx  # Bilibili Inc. [China] [game publisher]
  "#COIN":            ftx  # Coinbase Global Inc.
  "#FB":              ftx  # Facebook Inc.
  "#GBTC":            ftx  # Grayscale bitcoin trust
  "#GOOGL":           ftx  # Alphabet Inc.
  "#MSTR":            ftx  # MicroStrategy Inc.
  "#NIO":             ftx  # NIO Inc. [China] [electrocars]
  "#PYPL":            ftx  # PayPal Holdings
  "#TSLA":            ftx  # Tesla Inc.
  "#TWTR":            ftx  # Twitter Inc.
  "@gold":            ftx
  "@silver":          ftx

# list of assets to be accumulated when using --add with no additional parameters
auto_accumulate_list:
  - 0x
  - aave
  - arweave
  - avalanche-2
  - basic-attention-token
  - bitcoin
  - cosmos
  - curve-dao-token
  - decentraland
  - enjincoin
  - ethereum
  - ethereum-classic
  - fantom
  - ftx-token
  - gitcoin
  - harmony
  - havven
  - hedera-hashgraph
  - polkadot
  - ripple
  - solana
  - tezos
  - raydium
  - serum
  #- "#AAPL"
  #- "#AMZN"
  - "#BABA"
  - "#BILI"
  - "#COIN"
  #- "#FB"
  - "#GBTC"
  #- "#GOOGL"
  - "#MSTR"
  - "#NIO"
  #- "#PYPL"
  - "#TSLA"
  - "#TWTR"


# default quota for --add per asset if --qty is not specified
quota_usd: 50


# for auto-accumulate: quotas of individual assets will be lowered
# to ensure that sum of their usd value is not exceeding this parameter
total_quota_usd: 500

# applied unconditinally to quota_usd. The final factor is a product of all active factors.
quota_fixed_factor:
  "#AAPL":            0.2
  "#AMZN":            0.2
  "#BABA":            0.2
  "#BILI":            0.2
  "#COIN":            0.2
  "#FB":              0.2
  "#GBTC":            0.2
  "#GOOGL":           0.2
  "#MSTR":            0.2
  "#NIO":             0.2
  "#PYPL":            0.2
  "#TSLA":            0.2
  "#TWTR":            0.2
  "#SQ":              0.2

# moving average period to calculate average price to compare current price to
quota_factor_average_days: 200

# quota factor is upper limited to quota_factor_max
quota_factor_max: 2

# is True, asset from auto_accumulate_list is only processed if market is open at the moment
check_market_open: False

# if True, asset from auto_accumulate_list is only processed if today price < SMA(check_overprice_avg_days)
check_overprice: True
check_overprice_avg_days: 50

# list of assets that are not filtered under any condition
no_filter_list:
  - bitcoin
  - ethereum
