---

# map asset to exchange
asset_exchg:
  #crypto
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  shiba-inu:          poloniex
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  polkadot:           poloniex
  solana:             ftx
  ftx-token:          ftx
  decentraland:       okex
  tezos:              okex
  gitcoin:            bitrue
  basic-attention-token: poloniex
  enjincoin:          ftx
  fantom:             ftx
  hedera-hashgraph:   okex
  avalanche-2:        okex
  #stocks:
  "#AAPL":            ftx  # Apple Inc.
  "#AMZN":            ftx  # Amazon.com Inc.
  "#BABA":            ftx  # Alibaba Group Hldg (ADR) [China]
  "#BILI":            ftx  # Bilibili Inc. [China] [game publisher]
  "#COIN":            ftx  # Coinbase Global Inc.
  "#FB":              ftx  # Facebook Inc.
  "#GBTC":            ftx  # Grayscale bitcoin trust
  "#GOOGL":           ftx  # Alphabet Inc.
  "#MSTR":            ftx  # MicroStrategy Inc.
  "#NIO":             ftx  # NIO Inc. [China] [electrocars]
  "#PYPL":            ftx  # PayPal Holdings
  "#TSLA":            ftx  # Tesla Inc.
  "#TWTR":            ftx  # Twitter Inc.

# list of assets to be accumulated when using --add with no additional parameters
auto_accumulate_list:
  - bitcoin
  - ethereum
  - ripple
  - solana
  - gitcoin
  - curve-dao-token
  - aave
  - 0x
  - havven
  - ethereum-classic
  - ftx-token
  - decentraland
  - tezos
  - polkadot
  - basic-attention-token
  - enjincoin
  - fantom
  - hedera-hashgraph
  - avalanche-2
  #- "#AAPL"
  #- "#AMZN"
  - "#BABA"
  - "#BILI"
  - "#COIN"
  #- "#FB"
  - "#GBTC"
  #- "#GOOGL"
  - "#MSTR"
  - "#NIO"
  #- "#PYPL"
  - "#TSLA"
  - "#TWTR"


# default quota for --add per asset if --qty is not specified
quota_usd: 30


# quota_fixed_multiplier:
#   bitcoin: 0.3


# moving average period to calculate average price to compare current price to
quota_multiplier_average_days: 200


# quota multiplier is upper limited to quota_multiplier_max
quota_multiplier_max: 2


# asset from auto_accumulate_list is only processed if currently market is open or this parameter is True
accumulate_when_market_closed: True

# asset from auto_accumulate_list is only processed if dip has been detected or this parameter is True
accumulate_if_not_dipping: True
