---

# map asset to exchange
asset_exchg:
  #crypto
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  shiba-inu:          poloniex
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  polkadot:           poloniex
  basic-attention-token: poloniex
  solana:             ftx
  ftx-token:          ftx
  enjincoin:          ftx
  fantom:             ftx
  decentraland:       okex
  tezos:              okex
  hedera-hashgraph:   okex
  avalanche-2:        okex
  arweave:            mexc
  cosmos:             mexc
  gitcoin:            mexc
  harmony:            mexc
  #stocks:
  "#AAPL":            ftx  # Apple Inc.
  "#AMZN":            ftx  # Amazon.com Inc.
  "#BABA":            ftx  # Alibaba Group Hldg (ADR) [China]
  "#BILI":            ftx  # Bilibili Inc. [China] [game publisher]
  "#COIN":            ftx  # Coinbase Global Inc.
  "#FB":              ftx  # Facebook Inc.
  "#GBTC":            ftx  # Grayscale bitcoin trust
  "#GOOGL":           ftx  # Alphabet Inc.
  "#MSTR":            ftx  # MicroStrategy Inc.
  "#NIO":             ftx  # NIO Inc. [China] [electrocars]
  "#PYPL":            ftx  # PayPal Holdings
  "#TSLA":            ftx  # Tesla Inc.
  "#TWTR":            ftx  # Twitter Inc.


# list of assets to be accumulated when using --add with no additional parameters
auto_accumulate_list:
  - 0x
  - aave
  - avalanche-2
  - basic-attention-token
  - bitcoin
  - curve-dao-token
  - decentraland
  - enjincoin
  - ethereum
  - ethereum-classic
  - fantom
  - ftx-token
  - gitcoin
  - havven
  - hedera-hashgraph
  - polkadot
  - ripple
  - solana
  - tezos
  #- "#AAPL"
  #- "#AMZN"
  - "#BABA"
  - "#BILI"
  - "#COIN"
  #- "#FB"
  - "#GBTC"
  #- "#GOOGL"
  - "#MSTR"
  - "#NIO"
  #- "#PYPL"
  - "#TSLA"
  - "#TWTR"


# default quota for --add per asset if --qty is not specified
quota_usd: 60


quota_fixed_multiplier:
  0x:                       0.5
  basic-attention-token:    0.5
  decentraland:             0.5
  enjincoin:                0.5
  ethereum-classic:         0.5
  ftx-token:                0.5
  havven:                   0.5
  ripple:                   0.5
  "#BABA":                  0.2
  "#BILI":                  0.2
  "#COIN":                  0.2
  "#GBTC":                  0.2
  "#MSTR":                  0.2
  "#NIO":                   0.2
  "#TSLA":                  0.2
  "#TWTR":                  0.2


# moving average period to calculate average price to compare current price to
quota_multiplier_average_days: 200


# quota multiplier is upper limited to quota_multiplier_max
quota_multiplier_max: 2


# is True, asset from auto_accumulate_list is only processed if market is open at the moment
check_market_open: False

# if True, asset from auto_accumulate_list is only processed if today price is <= dip_threshold
check_dip: True
dip_threshold: -3
