---

# map asset to exchange
asset_exchg:
  #crypto
  bitcoin:            poloniex
  dogecoin:           poloniex
  ethereum:           poloniex
  matic-network:      poloniex
  cardano:            poloniex
  ripple:             poloniex
  shiba-inu:          poloniex
  curve-dao-token:    poloniex
  aave:               poloniex
  0x:                 poloniex
  havven:             poloniex
  ethereum-classic:   poloniex
  polkadot:           poloniex
  solana:             ftx
  ftx-token:          ftx
  decentraland:       okex
  tezos:              okex
  gitcoin:            bitrue
  #stocks:
  "#AAPL":            ftx
  "#AMZN":            ftx
  "#BABA":            ftx
  "#COIN":            ftx
  "#GOOGL":           ftx
  "#FB":              ftx
  "#MSTR":            ftx
  "#PYPL":            ftx

# list of assets to be accumulated when using --add with no additional parameters
auto_accumulate_list:
  - bitcoin
  - ethereum
  - ripple
  - solana
  - gitcoin
  - curve-dao-token
  - aave
  - 0x
  - havven
  - ethereum-classic
  - ftx-token
  - decentraland
  - tezos
  - polkadot
  #- "#AAPL"
  #- "#AMZN"
  - "#BABA"
  - "#COIN"
  #- "#GOOGL"
  #- "#FB"
  - "#MSTR"
  #- "#PYPL"



# default quota for --add per asset if --qty is not specified
quota_usd: 30


# quota_fixed_multiplier:
#   bitcoin: 0.3


# moving average period to calculate average price to compare current price to
quota_multiplier_average_days: 50


# quota multiplier is upper limited to quota_multiplier_max
quota_multiplier_max: 2
